### ISSUE TITLE
About the depth loss L_d

### ISSUE THREAD

**Issue by botaoye** [zju3dv/manhattan_sdf#1]
Hi, thanks for your wonderful work. I am not familiar with this area, so I have a question about the calculation of the depth loss L_d(Eq.7). Why only the set of camera rays going through image pixels that have depth values estimated by COLMAP are used for calculating the depth loss? why not use the depth of all pixels?

**Comment by ghy0324** [comment]
Hi! Thanks for your interest in our work!

COLMAP can provide accurate but sparse depth estimation, and the depth prediction is especially  incomplete in texture-less regions. Namely, only part of pixels have depth values in COLMAP prediction, other pixels are just of zero values. So we cannot calculate the depth loss for all pixels.

We have just upload our processed data to [Onedrive](https://zjueducn-my.sharepoint.com/:f:/g/personal/guohaoyu_zju_edu_cn/EqYvwsTjlcZIpA8CDlFYhKgBD57le2O_dHvpXF6zPv6Uyg?e=6FeMrC). Please download and checkout the COLMAP depth predictions under `depth_colmap/` folder of each scene. And we will soon provide an instruction on data preparation, including how to run COLMAP to generate sparse depth maps.

**Comment by botaoye** [comment]
It seems that I misunderstood Eq.7. Does it mean D(r) is the depth predicted by COLMAP rather than the ground truth provided by the dataset?

**Comment by ghy0324** [comment]
> It seems that I misunderstood Eq.7. Does it mean D(r) is the depth predicted by COLMAP rather than the ground truth provided by the dataset?

Yes. Our method does **NOT** use ground truth depth for reconstruction.

**Comment by botaoye** [comment]
Okay, thanks for your reply.
