### ISSUE TITLE
Running on Custom Dataset

### ISSUE THREAD

**Issue by soumyadipm** [zju3dv/manhattan_sdf#10]
A big thanks for this excellent work. The training script is running fine with the provided scannet dataset. But please instruct how to run your code on other scannet data and custom datasets too. Few specific questions:

1. Can I replace 'depth_colmap' with GT depth images provided in the ScanNet datasets? 
2.  How to generate semantic_deeplab data?
3. Any transformation needed fot the poses?

**Comment by ghy0324** [comment]
Hi! Thanks for your interest in our work!

For question 1: Of coarse you can! And in general the results will be better if you use GT depth images. Just remember to rescale the depth map (multiply the depth value by a ratio) if you normalize the camera poses.

For question 2 and 3: We have just provided a detailed instruction [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md). Hope it is helpful to you!

**Comment by junxiant** [comment]
> A big thanks for this excellent work. The training script is running fine with the provided scannet dataset. But please instruct how to run your code on other scannet data and custom datasets too. Few specific questions:
> 
> 1. Can I replace 'depth_colmap' with GT depth images provided in the ScanNet datasets?
> 2. How to generate semantic_deeplab data?
> 3. Any transformation needed fot the poses?

Hi, were you able to run it on your own custom dataset?
