### ISSUE TITLE
One issue regarding 3D reconstruction quality

### ISSUE THREAD

**Issue by jinmaodaomaye2021** [zju3dv/manhattan_sdf#13]
Hi @ghy0324 ,

Thanks for your work. I found one issue when I tried to reproduce your results.

I trained the model with your code from scratch using 50 epochs. Unfortunately, the 3D reconstruction quality is not as good as the one in the project page. It lacks texture details and the walls are bumpy at some parts. 

I also compared rendered images (at training camera poses) with the training images, and found that the rendered images are pretty blurry. Please check the sample images below.

![Screenshot from 2022-06-13 11-08-21](https://user-images.githubusercontent.com/89769436/173417079-c4b1d62c-1a36-4723-bc21-12099014f197.png)

![Screenshot from 2022-06-13 11-09-32](https://user-images.githubusercontent.com/89769436/173417276-a0b7e84c-b538-474e-89e8-46fff93d5504.png)

Could you please provide insights about this issue from your experience ?

BTW, it would be great if you can provide a pre-trained model as reference. 

Thanks.

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!

We have answered it in #12. Moreover, we have already provided our [reconstruction results](https://zjueducn-my.sharepoint.com/:f:/g/personal/guohaoyu_zju_edu_cn/ErmaGSfN0NlNgYSUfkGjNE8BkNvg77xqwJtz-9q1aJaVTw?e=hfI0rA) as well as the [pretrained models](https://zjueducn-my.sharepoint.com/:f:/g/personal/guohaoyu_zju_edu_cn/ErKnCXKbRa5Okkjivw4663kBJslVgGOSbM4rUxyIwKqZyw?e=TJvwTY).
