### ISSUE TITLE
which scene used in 7-scene?

### ISSUE THREAD

**Issue by LeeBY68** [zju3dv/manhattan_sdf#15]
hello,

In paper, the authors said 4 scenes are selected from 7-Scenes. Could you share the scene data used in 7-Scenes, as ScanNet?

Thank you very much.

**Comment by ghy0324** [comment]
Hi!

We provide the scene ids in the supplementary material, you can process them yourself following our [instruction](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md). We will upload our processed data later.
