### ISSUE TITLE
Pretrained semantic segmentation model's results look strange

### ISSUE THREAD

**Issue by kecol** [zju3dv/manhattan_sdf#16]
I've downloaded the pretrained model.pth file and used cuda 10.1, pytorch 1.6 and detectron 0.4 as it was required but the results on simple images look not good. Do you know what might be wrong here?

![image](https://user-images.githubusercontent.com/5040769/173823185-672bcda8-3a96-4f9e-b79b-fed937e3dd59.png)

**Comment by ghy0324** [comment]
Hi! We also noticed that the semantic segmentation predictions are not good, you can refer to the semantic maps in [our processed data](https://zjueducn-my.sharepoint.com/:f:/g/personal/guohaoyu_zju_edu_cn/EqYvwsTjlcZIpA8CDlFYhKgBD57le2O_dHvpXF6zPv6Uyg?e=6FeMrC). And that is one of the reasons why we design the joint optimization strategy.
