### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by botaoye** [zju3dv/manhattan_sdf#18]
Hi Authors, thanks for your work. After running "mesh extraction" I can get .obj files. I would like to ask what tools I can use to get the same visualization as Fig.5, Fig.11, and Fig.12 in your paper?
![image](https://user-images.githubusercontent.com/23137816/174469534-f9f235d5-dcf0-48fa-93a7-251d1928240f.png)

**Comment by ghy0324** [comment]
Hi! Just render the normal map. You may refer to https://stackoverflow.com/questions/45869953/meshlab-normalmap.
