### ISSUE TITLE
Problem occurs in training

### ISSUE THREAD

**Issue by LeeBY68** [zju3dv/manhattan_sdf#2]
Hello, thanks for the wonderful work !

There is something wrong when  training the net using:

`python train_net.py --cfg_file configs/scannet/0050.yaml gpus 0, exp_name scannet_0050`

the problem printed in the terminal is:

> File "train_net.py", line 119, in <module>
>     main()
>   File "train_net.py", line 115, in main
>     train(cfg, network)
>   File "train_net.py", line 70, in train
>     trainer.val(epoch, test_loader)
>   File "/home/manhattan_sdf/manhattan_sdf/lib/train/trainers/trainer.py", line 126, in val
>     mesh = extract_mesh(self.network.net.model.sdf_net, self.network.net.model.semantic_net)
>   File "/home/manhattan_sdf/manhattan_sdf/lib/utils/mesh_utils.py", line 115, in extract_mesh
>     sdf, level=level, spacing=[float(v) / N for v in volume_size]
>   File "/home/anaconda3/envs/manhattan_sdf/lib/python3.7/site-packages/skimage/measure/_marching_cubes_lewiner.py", line 137, in marching_cubes
>     mask=mask)
>   File "/home/anaconda3/envs/manhattan_sdf/lib/python3.7/site-packages/skimage/measure/_marching_cubes_lewiner.py", line 300, in _marching_cubes_lewiner
>     level = float(level)
> TypeError: float() argument must be a string or a number, not 'SemanticNet'

It seems two nets are fed into 'extract_mesh' function.
Can you tell me how to change the code to make it work fine?

Looking for your reply. Thank you!

**Comment by ghy0324** [comment]
Hi! Thank you for pointing this out. This is a bug due to historical reasons. You can just simply remove the second parameter fed into 'extract_mesh' function. We have fixed it in the [latest commit](https://github.com/zju3dv/manhattan_sdf/commit/650ed451f0a13576e1b1f2cf65282c4e4efef388).

**Comment by LeeBY68** [comment]
> extract_mesh

It works. Thank you !

**Comment by LeeBY68** [comment]
It works. Thank you !
