### ISSUE TITLE
Different offset & scale values when performing the camera normalization by myself

### ISSUE THREAD

**Issue by OasisYang** [zju3dv/manhattan_sdf#20]
Hi, appreciate for releasing the codes!  

I attempt to do the camera normalization step according to this [instruction](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md), but I cannot obtain the same offset and scale value provided by you. For instance, the provided offset and scale of scene0050_00 are [4.24910, 2.30138, 1.15986] and [0.40543], while the parameters I got are [4.2678, 2.2656, 1.2732] and [0.4167]. I directly borrowed the code from [VolSDF](https://github.com/lioryariv/volsdf/blob/main/data/preprocess/normalize_cameras.py) with some modifications to fit the format of scannet annotations.

They are slightly different, could you explain where the difference comes from and will it affect the final performance a lot?

Thanks a lot.

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
Do you use all frames or use 1/10 frames like [us](https://github.com/zju3dv/manhattan_sdf/blob/604944fd37cd8eb9045f4eb8ec4f994269981af4/docs/run_colmap/run.py#L39)? If you use all frames, maybe that's the reason.
And I don't think it will affect the final performance. Small perturbation can be tolerated as long as the requirements listed [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md#camera-poses) are fulfilled. Moreover, we will transform the extracted mesh to original coordinate [here](https://github.com/zju3dv/manhattan_sdf/blob/604944fd37cd8eb9045f4eb8ec4f994269981af4/run.py#L23), so the evaluation will not be affected by slightly different offset & scale values.

**Comment by OasisYang** [comment]
Hi, may I ask how to obtain the ground-truth scene mesh file? Seems the mesh file used in this work is different from the one provided by ScanNet.

**Comment by ghy0324** [comment]
> Hi, may I ask how to obtain the ground-truth scene mesh file? Seems the mesh file used in this work is different from the one provided by ScanNet.

The mesh provided by ScanNet is obtained by fusing all RGBD frames. Since we do not use all frames, we fuse the selected frames to make the evaluation more reasonable. And we recommend you to use [open3d](http://www.open3d.org/docs/release/tutorial/reconstruction_system/integrate_scene.html) for fusion if you want to run on custom data.

**Comment by LiXinghui-666** [comment]
> Hi, appreciate for releasing the codes!
> 
> I attempt to do the camera normalization step according to this [instruction](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md), but I cannot obtain the same offset and scale value provided by you. For instance, the provided offset and scale of scene0050_00 are [4.24910, 2.30138, 1.15986] and [0.40543], while the parameters I got are [4.2678, 2.2656, 1.2732] and [0.4167]. I directly borrowed the code from [VolSDF](https://github.com/lioryariv/volsdf/blob/main/data/preprocess/normalize_cameras.py) with some modifications to fit the format of scannet annotations.
> 
> They are slightly different, could you explain where the difference comes from and will it affect the final performance a lot?
> 
> Thanks a lot.

Hi, I want to ask how to calculate the offset and scale after the scale_mat is obtained from the original VolSDF code. Thanks a lot.
