### ISSUE TITLE
为什么我运行strain_net.py代码的时候GPU内存极其容易爆满？

### ISSUE THREAD

**Issue by qinli-jian** [zju3dv/manhattan_sdf#23]
你好：
我在按照文件构建好项目，运行strain_net.py的时候，12G显存一下子就满了，我修改了batch_size也是容易爆满显存，请问你训练的机子都是显存很高的吗？
谢谢！

**Comment by ghy0324** [comment]
我们是用单张12G显卡训练的。你的pytorch版本是多少？建议使用1.6，参考：#8

**Comment by czg-first** [comment]
好像主要是由于query sdf这个过程比较占内存，其实训练过程不是很占显存。
