### ISSUE TITLE
Scannet scenes used for training

### ISSUE THREAD

**Issue by yinlily12** [zju3dv/manhattan_sdf#24]
Hi, thanks for sharing the amazing work! 

I am curious about the number of scenes you used for training for the reconstruction task on the Scannet and 7-Scenes datasets .  Did you train the model on all scenes or just a few scenes for the reconstruction?

Looking forward to your reply.

**Comment by ghy0324** [comment]
Hi, thanks for your interest! Our method perform reconstruction by per-scene optimization, which is similar to NeRF, VolSDF and so on. So we do not train on some scenes for reconstruction task.
