### ISSUE TITLE
how to get the camera poses

### ISSUE THREAD

**Issue by Gary-Qinghua** [zju3dv/manhattan_sdf#26]
你好，对于自己的数据集经过colmap后，如何normalize the camera poses ；如果用原始的poses，可以吗
volsdf项目中的normalize_cameras.py 是对全局进行归一化得到一个normalize matrix, 你这个是针对每个场景都要进行normalize，得到对应的matrix，我最近才开始研究建模相关的深度学习论文，请给我一些建议，谢谢

**Comment by ghy0324** [comment]
处理的方法见[文档](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md)。另外，VolSDF是在DTU上做实验，DTU的所有场景camera pose是一样的，如果在其他数据做实验同样也要每个场景做normalize，这一点和我们方法没有本质区别。
