### ISSUE TITLE
Question about the difference between the pose of ScanNet and the processed data.

### ISSUE THREAD

**Issue by LinZhuoChen** [zju3dv/manhattan_sdf#27]
Thank you for your excellent work! 
I am now trying to train new scene of ScanNet using your model. I have found that there is some difference between the pose of ScanNet and your processed data's pose (in t parts). Could you share the process method of pose with me? Thanks~

**Comment by ghy0324** [comment]
Hi! Thanks for your interst! Please refer to the [document](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md) and the [script](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/run_colmap/run.py).

**Comment by LinZhuoChen** [comment]
Thank you for your kind reply~
