### ISSUE TITLE
Meaning of scale and offset?

### ISSUE THREAD

**Issue by mtk380** [zju3dv/manhattan_sdf#29]
In config file, what does the scale and offset mean? Thanks a lot!

` scale: 0.44963
    offset: [1.23815, 2.57319, 1.38001]`

**Comment by ghy0324** [comment]
Hi! Please refer to the ["Camera poses" part of the document](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md#camera-poses).
