### ISSUE TITLE
Data Download problem

### ISSUE THREAD

**Issue by 123AnthongDai321** [zju3dv/manhattan_sdf#3]
Sorry to bothter, but I can not download the ScanNet Data uploaded in OneDrive , could you upload to BaiduNetDisk or GoogleDrive ?

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
We have uploaded ScanNet Data to [Google Drive](https://drive.google.com/drive/folders/1VwnlvYe5ab-hz0AK2ugxWz3RiMFNA7Ot?usp=sharing) and [BaiduNetDisk](https://pan.baidu.com/s/1P5LWMvPzOLKiwEcMAjaDIw) (password: ap9k).

**Comment by 123AnthongDai321** [comment]
I can download ScanNet Data. Thank you so much !
