### ISSUE TITLE
Questions for preprocessing custom data

### ISSUE THREAD

**Issue by ghvision** [zju3dv/manhattan_sdf#30]
Thank you for your nice work!

I want to apply this work to my own data.

I have some images and their own camera poses, and can also get new poses from colmap.

However, regardless of the source of poses, their axis are not aligned with dominant axis, such as x, y, and z-axis.  

As far as I understand from you paper, our data must be aligned each axis by Manhattan-world assumption.

Is it okay just to use the colmap procedure you provide to apply your code to my data?

Thank you!

**Comment by ghy0324** [comment]
Hi! Thanks for your interest! And that’s a very good question.
In our experiments, we assume that the z-axis of the coordinate should be aligned with the z-axis of real-world, but we do not require x and y-axis also be aligned, that's the reason why we introduce a learnable normal direction for wall regions (eq.9 in our paper).
This setting is actually reasonable becasuse in practice, users can capture images using phone, the camera poses estimated by ARKit or ARCore can ensure that the z-axis is aligned with real-world thanks to the gravity sensor.
But this is not ensured if you use colmap to solve the camera poses, thanks for the heads up! To solve this problem, one way is to make n_f in eq.8 also be learnable and keep n_w vertical to n_f.
Hope this is helpful for you!

**Comment by ghvision** [comment]
Thank you for your kindness!
