### ISSUE TITLE
The coordinate of pose.txt?

### ISSUE THREAD

**Issue by mtk380** [zju3dv/manhattan_sdf#32]
I have read the data preperation guid. You said you get the pose from clomap, which means x points right, y points down, z points towards scene. If i use the blender data (x points right, y points up, z points towards scene), should i transform the pose to match yours like this?
`  # coordinate change

    location = np.array([bcam.matrix_world.decompose()[0]]).T

    R_bcam2world = np.array(bcam.matrix_world.decompose()[1].to_matrix())

    R_col2world = np.matmul(R_col2bcam, R_bcam2world)

    T_col2world = np.matmul(R_col2bcam,location)

    extrinsic = np.concatenate((R_col2world, T_col2world), axis=1)`

**Comment by ghy0324** [comment]
We use the pose provided by the datasets, which use the same definition of coordinate as colmap. And yes, you need to transform If you use blender data.
