### ISSUE TITLE
How do you get GT mesh?

### ISSUE THREAD

**Issue by Tangshitao** [zju3dv/manhattan_sdf#33]
The GT mesh in your data is different from the one in ScanNet, which is in very low quailty. How do you get the GT mesh?

**Comment by ghy0324** [comment]
We use TSDF fusion of open3d to fuse GT RGB-D data.

**Comment by Tangshitao** [comment]
Why don't you use the GT mesh provided in ScanNet. It's in much higher quality.

**Comment by ghy0324** [comment]
You can absolutely evaluate using the mesh provided by ScanNet. We fuse GT mesh ourselves for fair comparison, since we do not use all frames for reconstruction (for our method as well as all baselines), so we use the same frames to fuse GT mesh.
