### ISSUE TITLE
Run on my own data

### ISSUE THREAD

**Issue by DanielLiking** [zju3dv/manhattan_sdf#34]
Could you please tell me the detail steps of running the code on our own data? I am confused with how to prepare the data, like the intrinsic.txt. And I don't know why would this happen
![image](https://user-images.githubusercontent.com/90821850/202177820-154014f9-c330-4fa6-8a4a-66a4ca49ad7a.png)
My pics are all 756*504 but I met this mistake. I don't know how to fix it. I hope to receive your reply,THX!

**Comment by DanielLiking** [comment]
@zju3dv

**Comment by ghy0324** [comment]
Hi! Where do you get the `generate_poses.py` file?

**Comment by DanielLiking** [comment]
I wrote a .py file based on the author work

**Comment by ghy0324** [comment]
You may debug and check the shape of `masks`.

**Comment by DanielLiking** [comment]
I fixed it. And I wanna know how to get the pose/*.txt, can you help me out?

**Comment by ghy0324** [comment]
Solve the camera poses and save the 4x4 matrices using numpy.savetxt
