### ISSUE TITLE
为什么使用colmap重建深度信息时，会出现bug？

### ISSUE THREAD

**Issue by Cat-Lover-Yes** [zju3dv/manhattan_sdf#35]
因为我采用colmap重建相机位姿，所以我认为可以直接使用重建位姿的colmap模型，因此修改了run.py的代码。但当我这样做时，从fuse.ply.vis文件中读取信息的代码会报错，请问其中的原因是什么？或者，从fuse.ply.vis文件中读取信息的代码的作用是什么，能否提供注释？谢谢！
这是修改后的run.py主要代码
`for scene_id in ['214']:
    source = f'/data8T/ydf/manhattan_sdf/data/tmp/{scene_id}/'  # TODO: modify this to your path
    target = f'/data8T/ydf/manhattan_sdf/data/{scene_id}'
    
    os.makedirs(f'{target}/images', exist_ok=True)
    os.makedirs(f'{target}/pose', exist_ok=True)
    os.makedirs(f'{target}/depth_patchmatch', exist_ok=True)
    
    if not os.path.exists(f'{source}/images/10.jpg'):
        sortFile(source)
    
    colmap_path = "colmap"
    
    with open(f'{source}/colmap_output.txt', 'a') as f:
        feature_extractor_args = [
            colmap_path, 'feature_extractor',
            '--database_path', os.path.join(source, "database.db"),
            '--image_path', os.path.join(source, "images"),
            '--ImageReader.single_camera', '1',
            # '--ImageReader.mask_path', os.path.join(basedir, args.masks),
        ]
        feat_output = (subprocess.check_output(feature_extractor_args, universal_newlines=True))
        f.writelines(feat_output)
        print('Features extracted')

        exhaustive_matcher_args = [
            colmap_path, 'exhaustive_matcher',
            '--database_path', os.path.join(source, "database.db"),
        ]
        exh_output = (subprocess.check_output(exhaustive_matcher_args, universal_newlines=True))
        f.writelines(exh_output)
        print('Exhaustive matched')

        p = os.path.join(source, 'sparse')
        if not os.path.exists(p):
            os.makedirs(p)

        mapper_args = [
            colmap_path, 'hierarchical_mapper',
            '--database_path', os.path.join(source, "database.db"),
            '--image_path', os.path.join(source, "images"),
            # '--ImageReader.mask_path', os.path.join(basedir, args.masks),
            '--output_path', os.path.join(source, 'sparse'),
        ]

        map_output = (subprocess.check_output(mapper_args, universal_newlines=True))
        f.writelines(map_output)
        print('Sparse map created')

        os.makedirs(f'{source}/dense/', exist_ok=True)

        danse_args = [
            colmap_path, 'image_undistorter',
            '--image_path', os.path.join(source, "images"),
            # '--ImageReader.mask_path', os.path.join(basedir, args.masks),
            '--input_path', os.path.join(source, 'sparse', '0'),
            '--output_path', os.path.join(source, 'dense'),
            '--output_type', 'COLMAP',
        ]

        danse_output = (subprocess.check_output(danse_args, universal_newlines=True))
        f.writelines(danse_output)
        print('Danse map created')

        patch_args = [
            colmap_path, 'patch_match_stereo',
            '--workspace_path', os.path.join(source, 'dense'),
            '--workspace_format', 'COLMAP',
            '--PatchMatchStereo.cache_size', '64',
        ]

        patch_output = (subprocess.check_output(patch_args, universal_newlines=True))
        f.writelines(patch_output)
        print('Patch match stereo succeed')

        stereo_args = [
            colmap_path, 'stereo_fusion',
            '--workspace_path', os.path.join(source, 'dense'),
            '--workspace_format', 'COLMAP',
            '--input_type', 'geometric',
            '--output_path', os.path.join(source, 'dense', 'fused.ply'),
            '--StereoFusion.cache_size', '64',
        ]

        stereo_output = (subprocess.check_output(stereo_args, universal_newlines=True))
        f.writelines(stereo_output)
        print('Stereo fusion succeed')

    load_save_pose(source)
    npy2one(source)
    
    id_list = os.listdir(f'{source}/images')
    id_list = [id[:-4] for id in id_list if id.endswith('0.jpg')]
    id_list.sort(key=lambda _: int(_))
    
    pose_dict = dict()
    for id in id_list:
        pose_dict[id] = np.loadtxt(source + f'pose/{id}.txt')
    
    id_list = [id for id in id_list if not np.isinf(pose_dict[id]).any()]
    id_list.sort()
    
    translation_list = []
    for id in id_list:
        translation_list.append(pose_dict[id][None, :3, 3])
    translation_list = np.concatenate(translation_list)
    translation_center = (translation_list.max(axis=0) + translation_list.min(axis=0)) / 2
    translation_list -= translation_center
    max_cam_norm = np.linalg.norm(translation_list, axis=1).max()
    scale = (scale_radius / max_cam_norm / 1.1)
    
    for id in id_list:
        pose_dict[id][:3, 3] -= translation_center
        pose_dict[id][:3, 3] *= scale
    
    with open(f'{source}/offset.txt', 'w') as f:
        f.write(f'{translation_center}')
    
    with open(f'{source}/scale.txt', 'w') as f:
        f.write(f'{scale}')
    
    os.system(f'cp {source}/intrinsic.txt {target}/intrinsic.txt')
    
    for id in tqdm(id_list):
        color = cv2.imread(f'{source}/images/{id}.jpg')
        color = cv2.resize(color, (width, height))
        cv2.imwrite(f'{target}/images/{id}.png', color)
        np.savetxt(f'{target}/pose/{id}.txt', pose_dict[id])
    
    intrinsic = np.loadtxt(f'{target}/intrinsic.txt')
    
    images_bin_path = f'{source}/sparse/0/images.bin'
    images = read_images_binary(images_bin_path)
    names = [_[1].name for _ in images.items()]
    
    shape = (height, width)
    
    ply_vis_path = f'{source}/dense/fused.ply.vis'
    assert os.path.exists(ply_vis_path)
    masks = [np.zeros(shape, dtype=np.uint8) for name in names]
    load_point_vis(ply_vis_path, masks)
    
    for name, mask in tqdm(zip(names, masks)):
        depth_bin_path = f'{source}/dense/stereo/depth_maps/{name}.geometric.bin'
        if not os.path.exists(depth_bin_path):
            continue
        depth_fname = depth_bin_path
        depth = read_array(depth_fname)
        depth[mask == 0] = 0
        np.save(f'{target}/depth_patchmatch/{name[:-4]}.npy', depth)`

这是报错信息
`Traceback (most recent call last):
  File "/home/ydf/manhattan_sdf/docs/run_colmap/run.py", line 179, in <module>
    load_point_vis(ply_vis_path, masks)
  File "/home/ydf/manhattan_sdf/docs/run_colmap/run.py", line 33, in load_point_vis
    idx, u, v = struct.unpack('<III', f.read(4 * 3))
struct.error: unpack requires a buffer of 12 bytes`
其中的原因在于，按照你们提供的代码要求读取文件时，文件大小不匹配，导致不能读到更多信息

**Comment by Cat-Lover-Yes** [comment]
@zju3dv

**Comment by Cat-Lover-Yes** [comment]
另外，根据colmap官方的文档，.piy.vis文件内储存的是图片ids吗？
[scripts/python/read_write_fused_vis.py](https://github.com/colmap/colmap/blob/b02e93953ea4b6448e004524f65b82bf5e807c7c/scripts/python/read_write_fused_vis.py)
`def read_fused(path_to_fused_ply, path_to_fused_ply_vis):
    """
    see: src/mvs/meshing.cc
        void ReadDenseReconstruction(const std::string& path
    """
    assert os.path.isfile(path_to_fused_ply)
    assert os.path.isfile(path_to_fused_ply_vis)

    point_cloud = PyntCloud.from_file(path_to_fused_ply)
    xyz_arr = point_cloud.points.loc[:, ["x", "y", "z"]].to_numpy()
    normal_arr = point_cloud.points.loc[:, ["nx", "ny", "nz"]].to_numpy()
    color_arr = point_cloud.points.loc[:, ["red", "green", "blue"]].to_numpy()

    with open(path_to_fused_ply_vis, "rb") as fid:
        num_points = read_next_bytes(fid, 8, "Q")[0]
        mesh_points = [0] * num_points
        for i in range(num_points):
            num_visible_images = read_next_bytes(fid, 4, "I")[0]
            visible_image_idxs = read_next_bytes(
                fid, num_bytes=4*num_visible_images,
                format_char_sequence="I"*num_visible_images)
            visible_image_idxs = np.array(tuple(map(int, visible_image_idxs)))
            mesh_point = MeshPoint(
                position=xyz_arr[i],
                color=color_arr[i],
                normal=normal_arr[i],
                num_visible_images=num_visible_images,
                visible_image_idxs=visible_image_idxs)
            mesh_points[i] = mesh_point
        return mesh_points`

**Comment by ghy0324** [comment]
您好，我们在生成depth map时使用的并不是官方的colmap，而是[NerfingMVS](https://github.com/weiyithu/NerfingMVS)中使用的[改版](https://github.com/B1ueber2y/colmap/tree/c84269d693246d8294307cc32f851813f18b6a2d)，建议尝试一下这个版本。

**Comment by Cat-Lover-Yes** [comment]
> 您好，我们在生成depth map时使用的并不是官方的colmap，而是[NerfingMVS](https://github.com/weiyithu/NerfingMVS)中使用的[改版](https://github.com/B1ueber2y/colmap/tree/c84269d693246d8294307cc32f851813f18b6a2d)，建议尝试一下这个版本。

我已经在conda配置中指定了对应的colmap版本
`export LD_LIBRARY_PATH=/home/ydf/softwares/colmap_manhattan/build/__install__/lib:/home/ydf/softwares/colmap_manhattan/build/__install__/bin/colmap:$LD_LIBRARY_PATH
`

**Comment by Cat-Lover-Yes** [comment]
@zju3dv 我又再次删除所有配置，按照流程安装colmap、执行数据集生成程序，但是仍然出现以上问题。
因为没有服务器管理员权限，我是使用python脚本安装你们提供的特定版本colmap的，这与使用通常方式安装有什么区别吗？

**Comment by ghy0324** [comment]
不需要管理员权限，建议尝试使用源码编译得到可执行文件

**Comment by Cat-Lover-Yes** [comment]
@ghy0324 你好，我向你的邮箱发送了一份邮件，希望可以得到你的回复，谢谢！

**Comment by Cat-Lover-Yes** [comment]
我认为我发现了问题所在，当我用git clone命令从该特定版本colmap下载源代码时，得到了错误的结果，下载的代码并不是修改后的版本，而是原始的colmap代码。必须采用download zip的方式下载。
