### ISSUE TITLE
Training and running on custom dataset

### ISSUE THREAD

**Issue by bikhanal** [zju3dv/manhattan_sdf#36]
Thank you for this amazing work. 

I wanted to run this for a custom dataset. I prepared everything as recommended [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md). However I am stuck at the part where we need a ground truth mesh for training. How do I get that?

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
Ground truth mesh is only used for evaluation, it is not required for reconstruction.

**Comment by bikhanal** [comment]
@ghy0324 Thank you for you response. The training is running as expected now. However, I have problem getting an output. I prepared the dataset as recommended. 

Does the poses obtained from COLMAP needs to be inverted for training and how do I normalize those poses? Thank you in advance.

**Comment by ghy0324** [comment]
> @ghy0324 Thank you for you response. The training is running as expected now. However, I have problem getting an output. I prepared the dataset as recommended.
> 
> Does the poses obtained from COLMAP needs to be inverted for training and how do I normalize those poses? Thank you in advance.

Yes, you should invert the extrinsics (world to camera) to poses(camera to world). The way to normalize poses is detailed in the document.
