### ISSUE TITLE
something wrong with DDP

### ISSUE THREAD

**Issue by feiqiu-cyber** [zju3dv/manhattan_sdf#38]
when i run :
python -m torch.distributed.launch --nproc_per_node=4 train_net.py --cfg_file configs/scannet/0084.yaml  exp_name 0084
![image](https://user-images.githubusercontent.com/79258566/212361742-d4200500-6447-48ce-b4fc-99690d654148.png)

**Comment by ghy0324** [comment]
Sorry, our code currently does not support DDP. Our experiments are performed on single GPU.
