### ISSUE TITLE
depth on ScannetV2 dateset

### ISSUE THREAD

**Issue by murphyl4** [zju3dv/manhattan_sdf#39]
Hello!
I notice that the depth in ScannetV2 dateset is too large, almost larger than 1k. I have tried to normalize the depth by using (x - min) / (max - min), but the restruction and the metrics is terrible.
So I wonder how to normalize the depth, and which factors influence it.
Thanks!

**Comment by ghy0324** [comment]
Hi! The depth maps of ScanNet are in millimeters while the translations of camera poses are in meters. So just divide the depth values by 1000.
