### ISSUE TITLE
intrinsic.txt problem

### ISSUE THREAD

**Issue by Jinpeng-Yu** [zju3dv/manhattan_sdf#4]
Thanks for your excellent work!

I am new in this area, I have a question for the dataset detailed information. How do you get the 'intrinsic.txt' file? Do you extract the intrinsic parameters of camera by COLMAP tools?

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
Intrinsic parameters are provided by ScanNet dataset. They are obtained by running a calibration procedure, you may refer to [ScanNet paper](https://arxiv.org/abs/1702.04405) for more details.
