### ISSUE TITLE
Depth result of run_colmap is not same as provided depth data

### ISSUE THREAD

**Issue by weizhenFrank** [zju3dv/manhattan_sdf#41]
Hi, thanks for sharing the code to help us to run a modified version of colmap.  I download scannet data and use official python toolkit https://github.com/ScanNet/ScanNet/tree/master/SensReader/python to extract the data. 

Then I run the https://github.com/zju3dv/manhattan_sdf/blob/main/docs/run_colmap/run.py. 

However, when I check the consistency between your provided data and the result from above script. I found two differences.
1. The name of depth folder is depth_patchmatch rather than depth_colmap in provided data.
2. The depth image has different values between your provied data and the result from above script, such as the screenshot showed.
![image](https://user-images.githubusercontent.com/37463904/216793171-e6637312-c2b0-4a6d-bf3d-1a1979d28678.png)
In this screenshot, `pub10` is your provided data for 0050_00 scene of 10th image, `obj10` is the result from your script.
You can see that there's inconsistency. 
But the final metric is quite similar, as the screenshot shows. 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/37463904/216793270-ed3788fb-b970-4049-9fb1-4ff6ab42e524.png">

Here `Provided data` is your provided data and `From Scannet` is from downloaded scannet data. 

For the sake of rigorousness, I would like to know whether the difference is normal. I would appreciate a lot for your response!

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
The difference of depth folder names is due to some historical reasons, you can just change `patchmatch` to `colmap` in `run.py`. I’m not very sure why the depth values are different, maybe related to the version of COLMAP. But I think it’s OK if you can obtain similar final results.
