### ISSUE TITLE
Created groundtruth using your script is not good

### ISSUE THREAD

**Issue by weizhenFrank** [zju3dv/manhattan_sdf#42]
Hi, thanks for kind sharing your method of creating the ground truth mesh from scannet in this https://github.com/zju3dv/manhattan_sdf/issues/37#issuecomment-1380569950 !
I followed your [script](https://github.com/zju3dv/manhattan_sdf/blob/604944fd37cd8eb9045f4eb8ec4f994269981af4/lib/utils/mesh_utils.py#L50-L78) and made slight modification by your suggestion, which is as follows.
![image](https://user-images.githubusercontent.com/37463904/216877031-5cd72561-6e26-4858-b58d-7ecb326b6444.png)
Modifications are 
1. I didn't multiply `cfg.test_dataset.scale ` on `voxel_length` and `voxel_length`
2. I use ground truth depth and pose from scannet.
3. Divide the depth map by 1000

Except those three, others keep the same as your [script](https://github.com/zju3dv/manhattan_sdf/blob/604944fd37cd8eb9045f4eb8ec4f994269981af4/lib/utils/mesh_utils.py#L50-L78) .

But I found two differences. Take scene 0050_00 as an example.
1. There are some outliers of reconstructed scenes (visualized by [meshlab](https://www.meshlab.net/))
<img width="770" alt="image" src="https://user-images.githubusercontent.com/37463904/216877522-5943160a-016a-4a91-8eaa-2dca66fe0732.png">

The above ground truth is created by myself, the bottom is your provided.  

2. File size differs
![image](https://user-images.githubusercontent.com/37463904/216877876-6d20bd36-48a7-462d-a190-bdc9b8214b2e.png)

The first line was ground truth created by myself which is 4.5M , and the bottom is your provided which is 8.3 M.

I've checked all the issues for this repo but didn't find a solution. Could you please give me more instructions? Thanks for your help in advance!
    `

**Comment by weizhenFrank** [comment]
For the evaluation metric, I evaluated our GT over your provided GT. The result is as follows
<img width="752" alt="image" src="https://user-images.githubusercontent.com/37463904/216882633-115a6f62-ce62-43fc-b06d-72f157776bde.png">

We can see from Comp and Recal that our GT is a super set of your provided GT but with additional outliers.

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
We also noticed the problem of direct TSDF fusion. So we delete the floating vertices manually in meshlab. This operation will not affect the relative order of metrics of our method and baselines.

**Comment by weizhenFrank** [comment]
Thanks sooooo much! To make sure,  I just need to delete those outliers manually in meshlab, right?

**Comment by ghy0324** [comment]
Yes, you are right!
