### ISSUE TITLE
Question about the preparing custom data.

### ISSUE THREAD

**Issue by xiehousen** [zju3dv/manhattan_sdf#44]
I follow your description of [Run on custom data](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md).

I used colmap to generate `image.txt`, which contains pose. What should we do later? Is the pose processed with NeuS scheme?Or other things I need to do.

Thanks in advance.

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
Our document has included how to process the poses, please check it out. And of course you can process them with NeuS scheme.
