### ISSUE TITLE
Questions about training my own dataset

### ISSUE THREAD

**Issue by Gotta-C** [zju3dv/manhattan_sdf#47]
已经验证了0050_00数据集，在自己的数据集上训练，meshlab可视化没体现效果。图片帧数据采集一秒取5帧，ARcore pose转RT 4*4，相机内参，分割图没问题，深度估计数据也跑了NerfingMVS colmap，另外配置文件改了scale offset，还有什么需要对齐的？

**Comment by Gotta-C** [comment]
我下了scannet 0050_00 4650张图，跑run.py归一化结果是[4.2512515 2.300618  1.1593915] 0.4044493013154948，但是跑你的465张，[-2.22044605e-16 -5.55111512e-17  0.00000000e+00] 1.0。
图片数量会导致区别？理论上应该两者数值接近才对，所以我不确定在自己的场景里计算的scale正确不，最终的mesh效果如下
![image](https://user-images.githubusercontent.com/20768683/222033437-e4953339-da06-4431-b030-75a7df60dcfa.png)

**Comment by xiehousen** [comment]
我使用`Colmap`对`scannet_0050`的465张图计算Pose，但是使用这个`Pose`得到的渲染结果很差。有可能是1）本身465张图计算出的pose很差；2）pose的预处理不对；目前，我也没找到问题解决方案。如有结果可以讨论下

感觉你的结果还是因为pose不对引起的。

**Comment by Gotta-C** [comment]
> 

我找到465张pose 差别原因了，在执行run_colmap后pose做了归一化，并覆盖了之前的pose文件

**Comment by Gotta-C** [comment]
> 我使用`Colmap`对`scannet_0050`的465张图计算Pose，但是使用这个`Pose`得到的渲染结果很差。有可能是1）本身465张图计算出的pose很差；2）pose的预处理不对；目前，我也没找到问题解决方案。如有结果可以讨论下
> 
> 感觉你的结果还是因为pose不对引起的。

找到465张pose差别原因了，在执行run_colmap后pose做了归一化，并覆盖了之前的pose文件

**Comment by Gotta-C** [comment]
自己的数据在执行run_colmap最后处理深度图，其中depth shape(479,641),mask shape(480,640)， load_point_vis 和depth[mask == 0] = 0 存在越界

**Comment by xiehousen** [comment]
> > 我使用`Colmap`对`scannet_0050`的465张图计算Pose，但是使用这个`Pose`得到的渲染结果很差。有可能是1）本身465张图计算出的pose很差；2）pose的预处理不对；目前，我也没找到问题解决方案。如有结果可以讨论下
> > 感觉你的结果还是因为pose不对引起的。
> 
> 找到465张pose差别原因了，在执行run_colmap后pose做了归一化，并覆盖了之前的pose文件

我想问一下，你是自己生成的Pose？然后对Pose做归一化了吗？输入到模型中训练的Pose是做了归一化的还是没有做归一化的？

**Comment by Gotta-C** [comment]
> > > 我使用`Colmap`对`scannet_0050`的465张图计算Pose，但是使用这个`Pose`得到的渲染结果很差。有可能是1）本身465张图计算出的pose很差；2）pose的预处理不对；目前，我也没找到问题解决方案。如有结果可以讨论下
> > > 感觉你的结果还是因为pose不对引起的。
> > 
> > 
> > 找到465张pose差别原因了，在执行run_colmap后pose做了归一化，并覆盖了之前的pose文件
> 
> 我想问一下，你是自己生成的Pose？然后对Pose做归一化了吗？输入到模型中训练的Pose是做了归一化的还是没有做归一化的？
我理解一下，作者给的0050这个场景的pose数据是在scannet上下载，1/10抽样，并做了归一化，所以再对这批数据处理scale就是1，offset接近0。
我是处理自己的数据，pose需要自己生成的。目前还在训练，未确定是否转对。ARcore 位姿转4*4 RT矩阵，再按作者提供的转归一化方式处理

**Comment by czg-first** [comment]
> 自己的数据在执行run_colmap最后处理深度图，其中depth shape(479,641),mask shape(480,640)， load_point_vis 和depth[mask == 0] = 0 存在越界

我也发现了这个问题，用自己的数据集处理时，生成的geometric.bin的shape要比图片尺寸更大。根本原因在于进行了图片去畸变校正，导致图片尺寸有变化。因此最好是在输入前就做校正，这样相机模型也不用包含畸变参数了。

**Comment by Cat-Lover-Yes** [comment]
几位好！我想问个问题，使用colmap获得这个项目所需的pose，是执行下面的代码吗？我所保存的pose就是需要的吗？我接下来是否是只需要执行归一化就行了？ @Gotta-C @xiehousen @czg-first 
`def load_save_pose(realdir):
    # load colmap data
    model_path = os.path.join(realdir, 'sparse/0/')
    modeldata = read_model(model_path, ".bin")
    camdata = modeldata[0]
    
    list_of_keys = list(camdata.keys())
    cam = camdata[list_of_keys[0]]
    print('Cameras', cam)
    
    h, w, f = cam.height, cam.width, cam.params[0]
    hwf = np.array([h, w, f]).reshape([3, 1])
    
    imdata = modeldata[1]
    
    real_ids = [k for k in imdata]
    
    w2c_mats = []
    bottom = np.array([0, 0, 0, 1.]).reshape([1, 4])
    
    names = [imdata[k].name for k in imdata]
    print('Images #', len(names))
    
    perm = np.argsort(names)
    sort_names = [names[i] for i in perm]
    save_views(realdir, sort_names, isDelete=True)
    
    imgNameList = []
    for k in imdata:
        im = imdata[k]
        R = im.qvec2rotmat()
        t = im.tvec.reshape([3, 1])
        m = np.concatenate([np.concatenate([R, t], 1), bottom], 0)
        np.savetxt(os.path.join(realdir, "poses", im.name[:-3] + "txt"), m)
        w2c_mats.append(m)`
我在这里保存了世界坐标系中的点变换到相机坐标系中的变换矩阵，即w2c Matrix
