### ISSUE TITLE
The link to  download pretrained semantic segmentation model weight  is invalid~

### ISSUE THREAD

**Issue by DonVColreone** [zju3dv/manhattan_sdf#49]
Hello, I find the link to download the  weight of 2D semantic segmentation model  invalid, could you provide another one?

**Comment by DonVColreone** [comment]
![image](https://user-images.githubusercontent.com/118982607/229351260-de069691-96dd-4c77-ac25-d0d823582337.png)

**Comment by ghy0324** [comment]
Hi! Thanks for the heads up!
There is something wrong with my onedrive account, I will try to solve it and update the links soon. Here is a temporal google drive link of the model.
[https://drive.google.com/file/d/1sbboJHCMmFb1xzFBsf0ynfixJ1YcvT-r/view?usp=sharing](https://drive.google.com/file/d/1sbboJHCMmFb1xzFBsf0ynfixJ1YcvT-r/view?usp=sharing)
