### ISSUE TITLE
How to represent lens radial distortion with camera intrinsic matrix？

### ISSUE THREAD

**Issue by czg-first** [zju3dv/manhattan_sdf#50]
How to convert the interior parameters of colmap's SIMPLE_RADIAL camera model into a 4*4 interior parameter matrix? I saw that you said that when using custom data, camera intrinsic parameters should be saved to intrins.txt. But if there are camera distortion parameters, how to express them in a parameter matrix? Or do we just discard the distortion parameters?

**Comment by czg-first** [comment]
the tutorial of colmap indicate the small distortion can be ignored.
[_https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses_]

**Comment by ghy0324** [comment]
Hi! Unfortunately, camera distortion cannot be expressed by 4*4 intrinsic matrix. Maybe you can undistort the images first.
