### ISSUE TITLE
你们分享的语义分割的那个模型的链接失效了，能麻烦在分享一次吗

### ISSUE THREAD

**Issue by BruceAllenCS** [zju3dv/manhattan_sdf#51]

**Comment by ghy0324** [comment]
感谢您的提醒。现在可以通过这个链接下载
[https://drive.google.com/file/d/1sbboJHCMmFb1xzFBsf0ynfixJ1YcvT-r/view?usp=sharing](https://drive.google.com/file/d/1sbboJHCMmFb1xzFBsf0ynfixJ1YcvT-r/view?usp=sharing)
