### ISSUE TITLE
提供的result中的mesh结果的链接失效了，能麻烦再发一次吗

### ISSUE THREAD

**Issue by BruceAllenCS** [zju3dv/manhattan_sdf#52]

**Comment by ghy0324** [comment]
Sorry for the late reply.
Here is the google drive link.
[https://drive.google.com/file/d/1n5qqO9-uPTpYiWkeNRcsQrGiuJqoUxn9/view](https://drive.google.com/file/d/1n5qqO9-uPTpYiWkeNRcsQrGiuJqoUxn9/view)
