### ISSUE TITLE
One issue on the speed of training

### ISSUE THREAD

**Issue by yanchi-3dv** [zju3dv/manhattan_sdf#53]
Thanks for your work. I found one issue when I tried to reproduce your results.

I trained the model with one A100 card and torch 1.6. Unfortunately, Ten hours later, it's just training at epoch 3, step 3336.
<img width="1598" alt="image" src="https://github.com/zju3dv/manhattan_sdf/assets/96414864/a83453fa-559d-417a-afb8-a94283ed906d">

I noticed in your paper that “The optimization can be completed in about 5 hours for each scene.” I wonder if this five hours is the time to train 50 epochs or just one.

If it is the time to train 50 epochs, Is there any recommended way to improve the speed on my machine？

Thanks!!

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
"5 hours" is the time for 50 epochs, and I think it should be faster on A100.
As shown in your screenshot, it takes 9.8519 seconds for data loading, which is too slow. Maybe you could check the reason first.
Another suggestion: you could try to run other codes (such as nerf-pytorch, etc.) to see if it is an environmental problem.
