### ISSUE TITLE
2D的语义分割预训练权重链接已经过期，能麻烦您再放一下或者发一下吗

### ISSUE THREAD

**Issue by PinzhuoWu** [zju3dv/manhattan_sdf#54]

**Comment by PinzhuoWu** [comment]
![image](https://github.com/zju3dv/manhattan_sdf/assets/94941269/97c06e90-8ca9-4209-b302-c664ac2d1d2f)

**Comment by ghy0324** [comment]
抱歉带来不便，我们更新了链接
https://drive.google.com/file/d/1sbboJHCMmFb1xzFBsf0ynfixJ1YcvT-r/view?usp=sharing
