### ISSUE TITLE
请问为什么deeplab语义网络是输出41类？

### ISSUE THREAD

**Issue by duzh11** [zju3dv/manhattan_sdf#55]
nyu40标签里，有一个void类和其他40个语义类，正常做法不应该是忽略void类只在40类上进行训练吗？

**Comment by ghy0324** [comment]
还包括背景

**Comment by duzh11** [comment]
> 还包括背景

感谢回复，所以这篇工作的做法是对41类（把背景类也看成了一个单独语义类）训练?而不是忽略掉背景类（即你所说的背景类）

**Comment by ghy0324** [comment]
嗯，是的
