### ISSUE TITLE
How to build gt.obj

### ISSUE THREAD

**Issue by gaohongzhanghao** [zju3dv/manhattan_sdf#56]
Thank you for reading my questions. I would like to ask how to build a custom gt.obj file

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
Sensor depth maps are required for building gt.obj. You can use TSDF fusion to fuse multi-view depth maps. You may refer to this code.
https://github.com/zju3dv/manhattan_sdf/blob/c5e1503afdec8a50534d1022fecf9245dc9e99b5/lib/utils/mesh_utils.py#L50-L78
