### ISSUE TITLE
Inconsistent GT poses of provided scannet 0580_00 data

### ISSUE THREAD

**Issue by Willyzw** [zju3dv/manhattan_sdf#57]
Hi thanks for sharing the awesome code and data used in the paper. While processing the scannet 0580_00 data, I noticed the provided GT poses of this specific sequence differ from the poses in the original scannet dataset. 

The first pose from your side is
```
-1.665845499347471670e-01 4.856939306892101849e-01 -8.581090400494510995e-01 7.507216536898586590e-01
9.847348112464611170e-01 3.741256431312750541e-02 -1.699906449612836046e-01 -4.904711056204897890e-01
-5.045967569687923732e-02 -8.733274324926366683e-01 -4.845124341841562932e-01 6.246870167940057894e-02
0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00
```

while in original dataset is
```
-0.173572 0.307292 -0.935652 3.433624
0.984597 0.033894 -0.171520 0.967154
-0.020994 -0.951011 -0.308442 1.880443
0.000000 0.000000 0.000000 1.000000
```

Since I run SLAM algorithm, i.e. based on keyframes instead of every 10 frames, I need to align results to the original GT poses. But in this case, I could compare my reconstruction with your provided GT mesh. I wonder if you could upload an GT mesh version of original GT pose frame?

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
The difference is because z axis of 0580 scene in original ScanNet is not aligned correctly with gravity direction (while other 3 scenes are aligned correctly), so we rotate it to align manually.
You can transform the original poses to ours as follows:
```Python
pose_origin = ...
#[[-0.173572  0.307292 -0.935652  3.433624]
# [ 0.984597  0.033894 -0.17152   0.967154]
# [-0.020994 -0.951011 -0.308442  1.880443]
# [ 0.        0.        0.        1.      ]]

rotation = np.array([[ 9.81055493e-01, -3.73636465e-04, -1.93726561e-01],
                     [-3.73636465e-04,  9.99992631e-01, -3.82080710e-03],
                     [ 1.93726561e-01,  3.82080710e-03,  9.81048124e-01]])
translation = np.array([1.77986, 1.75840, 2.41183])
scale = 0.61330

pose_ours = np.eye(4)
pose_ours[:3] = rotation @ pose_origin[:3]
pose_ours[:3, 3] = (pose_ours[:3, 3] - translation) * scale

print(pose_ours)
#[[-0.16658455  0.48569393 -0.85810904  0.75071757]
# [ 0.98473481  0.03741256 -0.16999064 -0.49046881]
# [-0.05045968 -0.87332743 -0.48451243  0.0624674 ]
# [ 0.          0.          0.          1.        ]]
```
We provided translation and scale data [here](https://github.com/zju3dv/manhattan_sdf/blob/c5e1503afdec8a50534d1022fecf9245dc9e99b5/configs/scannet/0580.yaml#L50-L51) but did not provide rotation data, sorry for the inconveniency.
Hope this is helpful to you.

**Comment by Willyzw** [comment]
Thanks for sharing your insight, which has been very helpful! With the rotation you provided, I am now able to align my reconstruction with your gt mesh. 
I guess the translation and scale are only necessary when using the poses provided by this repo. Since I used the original GT poses, the translation and scale do not improve the alignment.
