### ISSUE TITLE
About result

### ISSUE THREAD

**Issue by HuTaoMylove** [zju3dv/manhattan_sdf#59]
![屏幕截图 2023-12-30 105953](https://github.com/zju3dv/manhattan_sdf/assets/88564974/1a3ab7a7-1919-4361-b782-5d2079f5eb7d)
![屏幕截图 2023-12-30 110016](https://github.com/zju3dv/manhattan_sdf/assets/88564974/ab8eb903-9ea7-4cce-b35c-4823757a4bb1)
Thank you for your work！I‘m confused about the difference in code and paper，why the metric in code higher than paper？

**Comment by ghy0324** [comment]
Hi! Thanks for your interest! We made some optimizations to the implementation details of the code. The methodology did not change, but the results showed some improvements compared to the beginning.
