### ISSUE TITLE
大佬，您好，相机参数是怎么得到的啊

### ISSUE THREAD

**Issue by wuxiaolianggit** [zju3dv/manhattan_sdf#6]
大佬，您好，相机参数是怎么得到的啊 @JiamingSuen @ybbbbt @pengsida @angshine @zehongs

**Comment by ghy0324** [comment]
您好，是数据集提供的。也可以通过跑COLMAP得到。

**Comment by wuxiaolianggit** [comment]
大佬，那在实地推理部署的时候，如何实时获得相机外参呢？@ @ghy0324
