### ISSUE TITLE
How to get scale and offset from colmap data?

### ISSUE THREAD

**Issue by fanwei360** [zju3dv/manhattan_sdf#61]
Thank you for your excellent work.
I have aligned the extracted mesh with colmap densely matched point cloud, how can I extract the scale and offset values from the colmap results to achieve alignment of their results? Thanks

**Comment by ghy0324** [comment]
Hi! Thank you for your interest in our work! And sorry for the late reply. The scale and offset are manually calculated and used for normalization.
https://github.com/zju3dv/manhattan_sdf/blob/c5e1503afdec8a50534d1022fecf9245dc9e99b5/docs/run_colmap/run.py#L49-L66
We also record the values of scale and offset and apply the inverse normalization operation to the mesh during the evaluation of the results.
