### ISSUE TITLE
The scale of colmap_depth

### ISSUE THREAD

**Issue by Dwawayu** [zju3dv/manhattan_sdf#62]
Hi, thank you for your amazing work!
In your guide for running on COLMAP data, I noticed that you [normalized the pose by a scale](https://github.com/zju3dv/manhattan_sdf/blob/c5e1503afdec8a50534d1022fecf9245dc9e99b5/docs/run_colmap/run.py#L60C7-L60C38) but did not do the same for the [COLMAP depth](https://github.com/zju3dv/manhattan_sdf/blob/c5e1503afdec8a50534d1022fecf9245dc9e99b5/docs/run_colmap/run.py#L155C1-L157C65). Why does this not result in a mismatch of scale between predicted depth and colmap depth when computing L1 loss?

**Comment by Dwawayu** [comment]
Oh! I just realized that you normalized the pose before dense reconstruction, right?

**Comment by ghy0324** [comment]
> Oh! I just realized that you normalized the pose before dense reconstruction, right?

Yes, we ran COLMAP based on the normalized camera poses.
