### ISSUE TITLE
The Coordinate System of Colmap Depth

### ISSUE THREAD

**Issue by LeeBY68** [zju3dv/manhattan_sdf#7]
Hi~

I would like to ask a question about the colmap depth input.
In one scene, does the depth value of each view input 'COLMAP depth map' under an unique world coordinate? 
or under the camera coordinate of each view frame?

Since original colmap tool outputs 'point3D.txt', how do you change the 3D points to depth?

Looking for your reply. Thank you!

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
We actually do not use information of 'points3D.txt'. We will provide an instuction later, which includes how to generate the depth maps. You may refer to #5 for the draft.
We generate the depth maps in the similar way with [NerfingMVS](https://github.com/weiyithu/NerfingMVS). You may refer to [this function](https://github.com/weiyithu/NerfingMVS/blob/b7f6590be69611c814822dc32e2220857c4d1dbf/utils/io_utils.py#L22).
Hope it is helpful to you.

**Comment by LeeBY68** [comment]
Thank you very much~ I will read files you mentioned. Waiting for your instructions !
