### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by hillaric** [zju3dv/manhattan_sdf#9]
When I run the code with pytorch 1.9 for evaluation, it appears this problem. And my memory is 8G, is it enough for evaluation?

**Comment by ghy0324** [comment]
Did you meet the problem in mesh extraction step?

**Comment by hillaric** [comment]
I success, but I find that each scene needs a model, which is a little different than what I thought, could you give some propositions about some general work for reconstruction.

**Comment by ghy0324** [comment]
> I success, but I find that each scene needs a model, which is a little different than what I thought, could you give some propositions about some general work for reconstruction.

NeuralRecon

**Comment by hillaric** [comment]
OK, I will have a try, I find some 3D sparse conv in NeuralRecon, but it can also run in real-time? It is incredibility！

**Comment by ghy0324** [comment]
Yes, it can.
